import React from "react";
import ConnectIcon from "components/ui/icons/NavIcons/ConnectIcon";
import ConnectionPoint from "components/ui/icons/NavIcons/ConnectionPoint";
import PureNaturalIcon from "components/ui/icons/NavIcons/PureNaturalIcon";
import EarthIcon from "components/ui/icons/NavIcons/EarthIcon";
import MonitorIcon from "components/ui/icons/NavIcons/MonitorIcon";
import BuildingFourIcon from "components/ui/icons/NavIcons/BuildingFourIcon";
import UserBusinessIcon from "components/ui/icons/NavIcons/UserBusinessIcon";
import RocketIcon from "components/ui/icons/NavIcons/RocketIcon";
import SunIcon from "components/ui/icons/NavIcons/SunIcon";
import NewspaperIcon from "components/ui/icons/NavIcons/NewspaperIcon";
import MonitorWithArrow from "components/ui/icons/NavIcons/MonitorWithArrow";
import WhiteLogo from "components/ui/icons/WhiteLogo";

const ASSETS_URL = "https://telecloud.b-cdn.net";

export const VERTICALS = [
  {
    id: 0,
    classname: "",
    icon: <EarthIcon size={34} />,
    largeIcon: <EarthIcon size={44} />,
    xLargeIcon: <EarthIcon size={80} />,
    url: "https://nftpowerup.io/",
    verticalsDescriptionComponentId: 1,
    showingDelay: 0.5,
    translateClass: "smallX",
    hasComponent: false,
    isLast: false,
    bg: `${ASSETS_URL}/web3.0_new.webp`,
  },
  {
    id: 1,
    classname: "blue",
    translateClass: "middleX",
    showingDelay: 0.7,
    icon: <ConnectionPoint size={34} />,
    largeIcon: <ConnectionPoint size={44} />,
    xLargeIcon: <ConnectionPoint size={80} />,
    url: "https://joyasmart.com/",
    hasComponent: false,
    verticalsDescriptionComponentId: 1,
    isLast: false,
    bg: `${ASSETS_URL}/IOT_new.webp`,
  },
  {
    id: 2,
    classname: "",
    translateClass: "largeX",
    showingDelay: 0.9,
    icon: <MonitorIcon size={34} />,
    largeIcon: <MonitorIcon size={44} />,
    xLargeIcon: <MonitorIcon size={80} />,
    url: "https://telecloudvision.com/",
    verticalsDescriptionComponentId: 1,
    hasComponent: true,
    isLast: false,
    bg: `${ASSETS_URL}/software_new.webp`,
  },
  {
    id: 3,
    classname: "blue",
    icon: <ConnectIcon size={34} />,
    showingDelay: 1.1,
    largeIcon: <ConnectIcon size={44} />,
    xLargeIcon: <ConnectIcon size={80} />,
    url: "http://fraudbin.com/",
    translateClass: "smallX",
    hasComponent: false,
    verticalsDescriptionComponentId: 2,
    isLast: false,
    bg: "https://telecloud.b-cdn.net/telecombg_new.webp",
  },
  {
    id: 4,
    classname: "",
    icon: <PureNaturalIcon size={34} />,
    showingDelay: 1.3,
    translateClass: "middleX",
    largeIcon: <PureNaturalIcon size={44} />,
    xLargeIcon: <PureNaturalIcon size={80} />,
    url: "http://frescagreen.com/",
    verticalsDescriptionComponentId: 2,
    hasComponent: false,
    isLast: false,
    bg: "https://telecloud.b-cdn.net/agriculture_new.webp",
  },
  {
    id: 5,
    classname: "",
    icon: <MonitorWithArrow size={34} />,
    showingDelay: 1.5,
    translateClass: "largeX",
    largeIcon: <MonitorWithArrow size={44} />,
    xLargeIcon: <MonitorWithArrow size={80} />,
    url: " https://hamsatapp.com/",
    verticalsDescriptionComponentId: 2,
    hasComponent: true,
    isLast: false,
    bg: "https://telecloud.b-cdn.net/digitalWelness_new.webp",
  },
  {
    id: 6,
    classname: "blue",
    translateClass: "smallX",
    showingDelay: 1.7,
    icon: <UserBusinessIcon size={34} />,
    largeIcon: <UserBusinessIcon size={44} />,
    xLargeIcon: <UserBusinessIcon size={80} />,
    url: "https://www.thinkmedialabs.com/",
    verticalsDescriptionComponentId: 3,
    hasComponent: false,
    isLast: false,
    bg: "https://telecloud.b-cdn.net/business_new.webp",
  },
  {
    id: 7,
    classname: "",
    icon: <RocketIcon size={34} />,
    showingDelay: 1.9,
    translateClass: "middleX",
    largeIcon: <RocketIcon size={44} />,
    xLargeIcon: <RocketIcon size={80} />,
    url: "http://startupvested.com/",
    verticalsDescriptionComponentId: 3,
    hasComponent: false,
    isLast: false,
    bg: "https://telecloud.b-cdn.net/statup_new.webp",
  },
  {
    id: 8,
    classname: "blue",
    showingDelay: 2.1,
    icon: <NewspaperIcon size={34} />,
    translateClass: "largeX",
    largeIcon: <NewspaperIcon size={44} />,
    xLargeIcon: <NewspaperIcon size={80} />,
    url: "http://mobilepasse.com/",
    verticalsDescriptionComponentId: 3,
    hasComponent: true,
    isLast: false,
    bg: "https://telecloud.b-cdn.net/media_new.webp",
  },
  {
    id: 9,
    classname: "",
    showingDelay: 2.3,
    icon: <SunIcon size={34} />,
    largeIcon: <SunIcon size={44} />,
    translateClass: "smallX",
    xLargeIcon: <SunIcon size={80} />,
    url: "https://joyasmart.com/smart-energy-saving-technology/",
    verticalsDescriptionComponentId: 4,
    hasComponent: false,
    isLast: false,
    bg: "https://telecloud.b-cdn.net/solar_new.webp",
  },
  {
    id: 10,
    showingDelay: 2.5,
    classname: "blue",
    translateClass: "middleX",
    icon: <BuildingFourIcon size={34} />,
    largeIcon: <BuildingFourIcon size={44} />,
    xLargeIcon: <BuildingFourIcon size={80} />,
    url: "/",
    verticalsDescriptionComponentId: 4,
    hasComponent: false,
    isLast: false,
    bg: "https://telecloud.b-cdn.net/realEstate_new.webp",
  },
  {
    id: 11,
    url: "",
    showingDelay: 2.7,
    classname: "",
    translateClass: "largeX",
    largeIcon: "",
    xLargeIcon: <WhiteLogo />,
    bg: "",
    icon: "",
    verticalsDescriptionComponentId: 4,
    hasComponent: true,
    isLast: true,
  },
];
